version: '3'
services:
  gdbserver:
    build:
      context: .
      args: 
        - BASE_IMAGE=ubuntu:bionic
      dockerfile: drake-torch.dockerfile
    image: dmsj/drake-torch:bionic_latest
    security_opt: # options needed for gdb debugging
      - seccomp:unconfined
      - apparmor:unconfined
    container_name: dexai_docker
    ports:
      - "7776:22"
      - "7777:7777"
      - "5920:5920"
      - "8097:8097" 
      - "8888:8888"
    environment:
      - DISPLAY=":20" 